# Generated by Django 2.2.5 on 2019-09-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=100)),
                ('EventDate', models.DateField()),
                ('Budget', models.FloatField()),
                ('Description', models.TextField()),
                ('NoOfParticipants', models.IntegerField()),
                ('Outcomes', models.TextField()),
            ],
        ),
    ]
